name: build and deploy  image

on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build the docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yussefmsabeh/app:dev
      - name: deploy to production
        uses: docker/metadata-action@v3
        with: yussefmsabeh/app:dev